

class Home_Locator:
    DEMOBLAZE = "https://www.demoblaze.com/"
    URL = "//body/nav[@id='narvbarx']/div[@id='navbarExample']/ul[1]"
    CART_LINK = "//a[@id='cartur']"
    HOME = "//body/nav[@id='narvbarx']/div[@id='navbarExample']/ul[1]/li[1]/a[1]"
    CONTACT = "//a[contains(text(),'Contact')]"
    LOGIN = "//a[@id='login2']"
    SIGNUP = "//a[@id='signin2']"
    ABOUT_US_LINK = "//a[contains(text(),'About us')]"
    PHONE = "//a[contains(text(),'Phones')]"
    LAPTOP = "//a[contains(text(),'Laptops')]"
    MACBOOK_AIR = "//a[contains(text(),'MacBook air')]"
    MONITOR = "//a[contains(text(),'Monitors')]"
    ASUS_FULL_HD = "//a[contains(text(),'ASUS Full HD')]"
    SUMSUNG_GALAXY_S6 = "//a[contains(text(),'Samsung galaxy s6')]"
    ADDTO_CART = "//a[contains(text(),'Add to cart')]"
    SUMSUNG_GALAXY = "//a[contains(text(),'Samsung galaxy s7')]"
    SONY_XPERIAL = "//a[contains(text(),'Sony xperia z5')]"
    BACK = "window.history.go(-2)"
    CART = "//a[@id='cartur']"
    PLACE_ORDER = "//button[contains(text(),'Place Order')]"
    NAME = "//input[@id='name']"
    BELAY = "belay"
    COUNTRY = "//input[@id='country']"
    CITY = "//input[@id='city']"
    CARD = "//input[@id='card']"
    MONTH = "//input[@id='month']"
    YEAR = "//input[@id='year']"
    PURCHASE = "//button[contains(text(),'Purchase')]"
    CLOSE = "//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"
    OK_BUTTON = "//button[contains(text(),'OK')]"
    ASSERT = "//button[contains(text(),'OK')]"
    LEFT_SIDE_BUTTON = "//body/nav[@id='narvbarx']/div[@id='contcar']/div[@id='carouselExampleIndicators']/a[2]/span[1]"
    RIGHT_SIDE_BUTTON = "//body/nav[@id='narvbarx']/div[@id='contcar']/div[@id='carouselExampleIndicators']/a[1]/span[1]"
    NEXT_BUTTON = "//button[@id='next2']"
    PREVIOUS_BUTTON = "//button[@id='prev2']"