
class Demo_Locator():
    DEMOBLAZE = "https://www.demoblaze.com/"
    URL = "//body/nav[@id='narvbarx']/div[@id='navbarExample']/ul[1]"
    PHONE = "//a[contains(text(),'Phones')]"
    SUMSUNG_GALAXY_S6 = "//a[contains(text(),'Samsung galaxy s6')]"
    ADDTO_CART = "//a[contains(text(),'Add to cart')]"
    BACK = "window.history.go(-3)"
    CART = "//a[@id='cartur']"
    PLACE_ORDER = "//button[contains(text(),'Place Order')]"
    NAME = "//input[@id='name']"
    COUNTRY = "//input[@id='country']"
    CITY = "//input[@id='city']"
    CARD = "//input[@id='card']"
    MONTH = "//input[@id='month']"
    YEAR = "//input[@id='year']"
    PURCHASE = "//button[contains(text(),'Purchase')]"
    OK_BUTTON = "//button[contains(text(),'OK')]"
    LAPTOP = "//a[contains(text(),'Laptops')]"
    MACBOOK_AIR = "//a[contains(text(),'MacBook air')]"
    MONITOR = "//a[contains(text(),'Monitors')]"
    ASUS_FULL_HD = "//a[contains(text(),'ASUS Full HD')]"
    LEFT_CLICK = "//body/nav[@id='narvbarx']/div[@id='contcar']/div[@id='carouselExampleIndicators']/a[2]/span[1]"
    RIGHT_CLICK = "//body/nav[@id='narvbarx']/div[@id='contcar']/div[@id='carouselExampleIndicators']/a[1]/span[1]"
    NEXT_BUTTON = "//button[@id='next2']"
    PREVIOUS = "//button[@id='prev2']"
    EMAIL = "//input[@id='recipient-email']"
    NAME1 = "//input[@id='recipient-name']"
    MESSAGE = "//textarea[@id='message-text']"
    SEND_BUTTON = "//button[contains(text(),'Send message')]"
    ABOUT_US_SELECT = "//body/div[@id='videoModal']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]"
    ABOUT_PAUSE_BUTTON = "//body/div[@id='videoModal']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[4]/button[1]/span[1]"
    SPEAKOR_BUTTON = "//body/div[@id='videoModal']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[4]/div[1]/button[1]/span[1]"
    ZOOM_BUTTON = "//body/div[@id='videoModal']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[4]/button[4]/span[1]"
    TIMER_BUTTON = "//body/div[@id='videoModal']/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[4]/div[5]"
    CLOSE_BUTTON = "//body/div[@id='videoModal']/div[1]/div[1]/div[3]/button[1]"
    DELETE = "//a[contains(text(),'Delete')]"
    LOGIN_USERNAME = "//input[@id='loginusername']"
    LOGIN_PASSWORD = "//input[@id='loginpassword']"
    LOGIN_BUTTON = "//button[contains(text(),'Log in')]"
    SIGNUP_USERNAME = "//input[@id='sign-username']"
    SIGNUP_PASSWORD = "//input[@id='sign-password']"
    SIGNUP_BUTTON = "//button[contains(text(),'Sign up')]"


